name: invisible-flow-env
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15=0
  - certifi=2019.3.9=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1c=h1de35cc_1
  - pip=19.1.1=py37_0
  - python=3.7.3=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.28.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/adeolu-works/miniconda3/envs/invisible-flow-env

